---
  extends: "eslint:recommended"

  parser: "babel-eslint"


  plugins:
    - vue

  parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
      modules: true
    sourceType: "module"

  rules:
    no-unused-vars:
      - 1
      - vars: all
        args: none
    no-console: 1
    semi: 1
    comma-dangle:
        - 1
        - "only-multiline"
#    no-alert: 0
#    no-bitwise: 0
#    camelcase: 1
#    curly: 1
#    eqeqeq: 0
#    no-eq-null: 0
#    guard-for-in: 1
#    no-empty: 1

  globals:
    global: false,
    $: false,
    require: false,
    Promise: false,
    Phaser: false,
    Symbol: false,
    game: false,
    process: false,

  env:
    browser: true
#    commonjs: true
#    es6: true
